apiVersion: v1
kind: Service
metadata:
  name: current-time-service
  namespace: kuber-time
spec:
  selector:
    app: current-time
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # type: LoadBalancer